src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $nickname;
    
    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;
    
    /**
     * @ORM\Column(type="integer")
     */
    private $cantidad;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Skins;
    
    
//ASOCIACIONES
    
    /**
     * Many Users have Many Users.
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="myFriends")
     */
    private $friendsWithMe;

    /**
     * Many Users have many Users.
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="friendsWithMe")
     * @ORM\JoinTable(name="friends",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="friend_user_id", referencedColumnName="id")}
     *      )
     */
    private $myFriends;
    //CONSTRUCTOR
    public function __construct() {
        $this->friendsWithMe = new ArrayCollection();
        $this->myFriends = new ArrayCollection();
        $this->Skins = new ArrayCollection();
        $this->roles = ['ROLE_USER'];
        $this->cantidad = 100;
    }
    //GETTTERS AND SETTERS
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): self
    {
        $this->nickname = $nickname;

        return $this;
    }
    function getEmail() {
        return $this->email;
    }
     public function getCantidad(): ?int
    {
        return $this->cantidad;
    }

    public function setCantidad(int $cantidad): self
    {
        $this->cantidad = $cantidad;

        return $this;
    }

    public function getSkins(): ?string
    {
        return $this->Skins;
    }

    public function setSkins(string $Skins): self
    {
        $this->Skins .= ' '.$Skins;

        return $this;
    }
    function getFriendsWithMe() {
        return $this->friendsWithMe;
    }

    function getMyFriends() {
        return $this->myFriends;
    }

    function setEmail($email) {
        $this->email = $email;
    }

    function setFriendsWithMe($friendsWithMe) {
        $this->friendsWithMe = $friendsWithMe;
    }

    function setMyFriends($myFriends) {
        $this->myFriends = $myFriends;
    }

        /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->nickname;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/PerfilController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class PerfilController extends AbstractController
{
    /**
     * @Route("/perfil", name="perfil")
     */
    public function index()
    {
        $user = $this->getUser();
        return $this->render('perfil/index.html.twig', [
            'nickerror' => '',
            'emailerror' => '',
            'controller_name' => 'Perfil',
            'user' => $user,
        ]);
    }
    /**
     * @Route("/cambiaNick", name="cambiaNick")
     */
    public function cambiaNick()
    {
        $existe=false;
        $nickerror = '';
        $em = $this->getDoctrine()->getManager();
        $nickname = $_POST['nickname'];
        $user = $this->getUser();
        $usuarios = $em->getRepository(User::class)->buscarPorCampo('nickname', $nickname);
        
        if($nickname){
            for($i=0;$i < count($usuarios);$i++){
                if($usuarios[$i] == $nickname){
                    $existe=true;
                    break;
                }
            }
            if($existe){
                $nickerror = 'Nick en uso, por favor elija otro';   
            }else{
                $user->setNickname($nickname);
                $em->persist($user);
                $em->flush();
            }
        }
        return $this->render('perfil/index.html.twig', [
            'user' => $user,
            'emailerror' => '',
            'controller_name' => 'Perfil',
            'nickerror' => $nickerror
        ]);
    }
    /**
     * @Route("/cambiaEmail", name="cambiaEmail")
     */
    public function cambiaEmail()
    {
        $existe=false;
        $emailerror = '';
        $em = $this->getDoctrine()->getManager();
        $email = $_POST['email'];
        $user = $this->getUser();
        $usuarios = $em->getRepository(User::class)->buscarPorCampo('email', $email);
        
        if($email){
            for($i=0;$i < count($usuarios) ;$i++){
                console.log($usuarios[$i]);
                if($usuarios[$i] == $email && isset($email)){
                    $existe=true;
                    break;
                }
            }
            if($existe){
                $emailerror = 'Email en uso, por favor elija otro';
            }else{
                $user->setEmail($email);
                $em->persist($user);
                $em->flush();
            }
        }
        return $this->render('perfil/index.html.twig', [
            'user' => $user,
            'nickerror' => '',
            'controller_name' => 'Perfil',
            'emailerror' => $emailerror
        ]);
    }
    /**
     * @Route("/cambiaPass", name="cambiaPass")
     */
    public function cambiaPass(UserPasswordEncoderInterface $passwordEncoder)
    {
        $em = $this->getDoctrine()->getManager();
        $password = $_POST['password'];
        $user = $this->getUser();
        if($password){
            $user->setPassword($passwordEncoder->encodePassword($user,$password));
            $em->persist($user);
            $em->flush();
        }
        
        return $this->render('perfil/index.html.twig', [
            'user' => $user,
            'nickerror' => '',
            'emailerror' => '',
            'controller_name' => 'Perfil',
        ]);
    }
}

templates/perfil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PerfilController!{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}
{% block body %}
    {{ parent() }}
    <div class="example-wrapper">
        <ul id="listaPerfil">
            <li>
                <h1>{{ controller_name }}</h1>
                <form action="cambiaPass" method="post" enctype="multipart/form-data">
                    <input type="text" name="password" Placeholder="Password" class='col-3 mx-auto'>
                    <input type="submit" class='col-3 mx-auto' value="Cambiar contraseña">
                </form>
            </li>
            <li>
                <h2>Nickname</h2>
                <p class="text-danger">{{ nickerror }}</p>
                <p>{{ user.nickname }}</p>
                <form action="cambiaNick" method="post" enctype="multipart/form-data">
                    <input type="text" name="nickname" Placeholder="Nickname" class='col-3 mx-auto'>
                    <input type="submit" class='col-3 mx-auto' value="Cambiar nick">
                </form>
            </li>
            <li>
                <h2>Email</h2>
                <p class="text-danger">{{ emailerror }}</p>
                <p>{{ user.email }}</p>
                <form action="cambiaEmail" method="post" enctype="multipart/form-data">
                    <input type="text" name="email" Placeholder="Email" class='col-3 mx-auto'>
                    <input type="submit" class='col-3 mx-auto' value="Cambiar email">
                </form>
            </li>
            <li>
                <h2>Monedas</h2>
                <p>{{ user.cantidad }}</p>
            </li>
            <li>
                <h2>Skins</h2>
                {% for i in user.skins %}
                    <p>{{ i }}</p>
                {% endfor %}
            </li>
            <li>

            </li>
        </ul>
    </div>
{% endblock %}
{% block footer %}
    {{ parent() }}
{% endblock %}
{% block javascripts %}
    {{ parent() }}
{% endblock %}